#in boot spring apps, we get this file with the name "application.properties" and we should change it to "yml"
#and this is what we got from "spring.io" to create our "application.properties" file:
#spring:jpa.hibernate.ddl-auto=create
#spring.datasource.url=jdbc:mysql://localhost:3306/online-shop
#spring.datasource.username=online-shop-admin
#spring.datasource.password=1234abc
#But we need to do some changes to the code as we changed the name of the file as follows:

spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/social-network?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: social-network-admin
    password: abcd123

# by default the port of this app was 8080, to change it we add what follows:
server:
  port: 8086
